export default [
    {
      question: "Em que ano aconteceu o atentado às Torres Gêmeas em Nova York?",
      answers: [
        { option: "2000", correct: false },
        { option: "2001", correct: true },
        { option: "2003", correct: false },
        { option: "1999", correct: false },
      ],
    },
    {
      question: "Qual país sediou os Jogos Olímpicos de 2004?",
      answers: [
        { option: "China", correct: false },
        { option: "Grécia", correct: true },
        { option: "Austrália", correct: false },
        { option: "Brasil", correct: false },
      ],
    },
    {
      question: "Em que ano a Guerra do Iraque começou?",
      answers: [
        { option: "2003", correct: true },
        { option: "2001", correct: false },
        { option: "2005", correct: false },
        { option: "2002", correct: false },
      ],
    },
    {
      question: "Qual furacão devastou Nova Orleans em 2005?",
      answers: [
        { option: "Katrina", correct: true },
        { option: "Rita", correct: false },
        { option: "Sandy", correct: false },
        { option: "Wilma", correct: false },
      ],
    },
    {
      question: "Qual país foi o principal afetado pelo tsunami de 2004?",
      answers: [
        { option: "Indonésia", correct: true },
        { option: "Tailândia", correct: false },
        { option: "Sri Lanka", correct: false },
        { option: "Índia", correct: false },
      ],
    },
    {
      question: "Em que ano foi lançado o primeiro iPhone?",
      answers: [
        { option: "2007", correct: true },
        { option: "2005", correct: false },
        { option: "2009", correct: false },
        { option: "2006", correct: false },
      ],
    },
    {
      question: "Qual presidente dos EUA foi eleito em 2008?",
      answers: [
        { option: "Barack Obama", correct: true },
        { option: "George W. Bush", correct: false },
        { option: "Bill Clinton", correct: false },
        { option: "John McCain", correct: false },
      ],
    },
    {
      question: "Em que ano o Facebook foi fundado?",
      answers: [
        { option: "2004", correct: true },
        { option: "2006", correct: false },
        { option: "2008", correct: false },
        { option: "2005", correct: false },
      ],
    },
    {
      question: "Qual empresa de tecnologia lançou o Xbox 360 em 2005?",
      answers: [
        { option: "Microsoft", correct: true },
        { option: "Sony", correct: false },
        { option: "Nintendo", correct: false },
        { option: "Sega", correct: false },
      ],
    },
    {
      question: "Qual evento mundial de música foi realizado em 2005, voltado para a erradicação da pobreza?",
      answers: [
        { option: "Live 8", correct: true },
        { option: "Woodstock", correct: false },
        { option: "Coachella", correct: false },
        { option: "Rock in Rio", correct: false },
      ],
    },
  ];
  